### ISSUE TITLE
MIT License and copyright

### ISSUE THREAD

**Issue by kcartlidge** [mohannadize/nodepub-lite#1]
Hi.
I'm glad you like Nodepub and I appreciate the very positive comment in the README file.

It's MIT licensed so you're free to do what you want with it, obviously.  That said, the MIT License is only _almost_ a total giveaway of rights - the main right that is reserved is the copyright one.  I'm sure it's an oversight but the license does state "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

The license file in your repo only has _your_ copyright on it, whereas the code prior to your changes was under _my_ copyright and according to the license that needs acknowledging.  The custom when building on existing MIT code is to include multiple copyrights where necessary and fortunately in this case there is a clear dated cut-off so an easy solution would be something along the lines of the following:

---
MIT License

Copyright (c) 2022 Mohanad Hesham
Copyright (c) 2019-2021 kcartlidge

...
---

As I say, I'm sure it's an oversight.  I'd greatly appreciate you updating it when you get a moment. Thanks!

**Comment by mohannadize** [comment]
Hi, I am sorry I don't have enough knowledge of the open-source community.
I will update the LICENCE file with the noted changes.

And thank you again for your awesome work! :smile:

**Comment by kcartlidge** [comment]
No worries; I presumed it was just an oversight and didn't take offence :)
